{% set version = "2.7.1" %}
{% set sha256 = "9b7b16e26448b43cf167f785d8b5345007731ebf153a510e12dae826800caa65" %}

package:
  name: psycopg2
  version: {{ version }}

source:
  fn: psycopg2-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/psycopg2/psycopg2-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - have_openssl.patch

build:
  number: 0
  script: python setup.py install  # [win]

requirements:
  build:
    - python
    - openssl 1.0.*
    - postgresql
  run:
    - python
    # libpq is a repackaging of only the library to connect to postgres
    - libpq
    - openssl 1.0.*

test:
  imports:
    - psycopg2
    - psycopg2._psycopg

about:
  home: http://initd.org/psycopg/
  license: LGPL, BSD-like, ZPL
  summary: 'Python-PostgreSQL Database Adapter'

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
