{% set name = "psycopg" %}
{% set version = "3.3.1" %}

package:
  name: psycopg-split
  version: {{ version }}

source:
  - folder: psycopg
    url: https://pypi.org/packages/source/p/psycopg/psycopg-{{ version }}.tar.gz
    sha256: ccfa30b75874eef809c0fbbb176554a2640cc1735a612accc2e2396a92442fc6
    patches:
      - 0001-remove-tzdata-for-pip-check.patch

  - folder: psycopg-c
    url: https://pypi.org/packages/source/p/psycopg-c/psycopg_c-{{ version }}.tar.gz
    sha256: 0c49958297578e5dbf9a7e7dabe7a03cac0290b70dd612ece5fa9f10ae6a0dea

build:
  number: 0

requirements:
  host:
    - python
  run:
    - python

outputs:

  - name: psycopg-c
    build:
      script: cd psycopg-c && {{ PYTHON }} -m pip install . -vv  --no-deps --no-build-isolation

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - postgresql                             # [build_platform != target_platform]
      host:
        - python
        - pip
        - libpq
        # conda-forge didn't build 80.3.1, so pin the lowest available higher version
        - setuptools ==80.8.0
      run:
        - libpq
        - python
    test:
      commands:
        - pip check
      requires:
        - pip

  - name: psycopg
    build:
      script: cd psycopg && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
      noarch: python
      # NOTE: must be kept equal to python_min
      skip: true  # [not linux64 or py!=310]

    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools >=80.3.1
        - libpq
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage('psycopg-c', max_pin='x.x.x.x.x.x') }}
        # for python <3.13 but keeping it for all to stay noarch: python
        - typing-extensions >=4.6
        - libpq
        # skipping tzdata based on https://github.com/conda-forge/psycopg2-feedstock/pull/120
        # so we don't have to build separately for windows
    test:
      imports:
        - psycopg
        - psycopg.pq
        - psycopg_c
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

about:
  home: https://psycopg.org/psycopg3/
  summary: PostgreSQL database adapter for Python
  description: |
    Psycopg 3 is a newly designed PostgreSQL database adapter for the Python
    programming language. Psycopg 3 presents a familiar interface for everyone
    who has used Psycopg 2 or any other DB-API 2.0 database adapter, but allows
    to use more modern PostgreSQL and Python features.
  license: LGPL-3.0-only
  license_file: psycopg/LICENSE.txt
  doc_url: https://www.psycopg.org/psycopg3/docs/
  dev_url: https://github.com/psycopg/psycopg/

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
    - xylar
