{% set name = "psycopg2" %}
{% set version = "2.9.11" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/psycopg2/psycopg2-{{ version }}.tar.gz
  sha256: 964d31caf728e217c697ff77ea69c2ba0865fa41ec20bb00f0977e62fdcc52e3
  patches:
    - 0001-have-openssl.patch

build:
  number: 0

outputs:
  - name: {{ name }}
    script: install_psycopg2.sh  # [unix]
    script: install_psycopg2.bat  # [win]
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - postgresql                             # [build_platform != target_platform]
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
      host:
        - python
        - setuptools
        - pip
        - openssl  # [not linux]
        - postgresql
      run:
        - python
        # libpq is a repackaging of only the library to connect to postgres
        - libpq
        - openssl  # [not linux]

    test:
      imports:
        - psycopg2
        - psycopg2._psycopg
      commands:
        - pip check
      requires:
        - pip

  # alternative name for the package, patched to rename the package in the
  # metadata so pip check will pass for packages that depend on pyscopg2-binary
  - name: psycopg2-binary
    script: install_psycopg2-binary.sh
    build:
      noarch: python
      skip: true  # [not linux or py!=39 or ppc64le or aarch64]
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
    test:
      imports:
        - psycopg2
      commands:
        - pip check
      requires:
        - pip
        - python {{ python_min }}

about:
  home: http://initd.org/psycopg/
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: PostgreSQL database adapter for Python
  description: |
    Psycopg is the most popular PostgreSQL adapter for the Python programming
    language. Its main features are the complete implementation of the Python DB
    API 2.0 specification and the thread safety.
  doc_url: http://initd.org/psycopg/docs/
  doc_source_url: https://github.com/psycopg/psycopg2/blob/master/doc/src/index.rst
  dev_url: https://github.com/psycopg/psycopg2/

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
    - xylar
