appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: azure, win: azure}
travis:
  secure: {BINSTAR_TOKEN: Vi7UX9hlfQHFbXyoQ2HmJdmTikdIAmONllOS4LV5XvqE3att+R+rP3lOg2TDN8azneISP9QX7VBYLfqN5zMr5ZJA8HcC3D88/Q+eirVQEoT8RievdYdeR4KOEiKfJ5Nha9+KT++oFCX60iOFhQ8V2EwhaCLzWQpJ/6lW3gUdU1N42I5tbCMKeFJ8XGPofXDaTxd3FWES5PSbm0hx9gLalLa2pAH45ak/rzcEk3hubIvHrGKyeEHkqcakbavkfTaAWNwK8XnZAGIAJOoL19nzXNB7MZ8Izx/AHxrG3uykmG/oTH5V2hQ6ewxUe3+NuUVnnU/u7kKSK2TxQyBB5FaOGF5x5tlsvE1at8Y5bpY88DAKfQxx4gypCTlag94gPnxPP1/70mHTZCH0ePal/ykY7BrXuygcfLsPKmqIWNEkwa5NG+1UqQuF6aXtoe12jeHLJOGrfIGacM4Nkfw8aZa0fPL/GU3oQpwOBM13Tnvw+zbwVrIb4UuUb3QBFNjO//4KV5YfKmcKWjWsAfkUO/QjtI1HvGhsT19g/tKVTTM6OSl7tRpfepRwGTNjQQJDutiPbjvnbw2uh+CATB//4umiq/3m+N4W59bkj0+9RN6KivCXJc31uid7Npn10m6Y0Mx4FvW+d2cuOQWL9o6l8h6jN1nnN4u1AEWgxeiEzgeqigI=}
